export const STRAYS = [
  {
    id: 1,
    name: "Charlie",
    breed: "Mixed Breed",
    gender: "Male",
    age: "~2 years",
    weight: "15 kg",
    location: "Engineering Building",
    rescueDate: "August 12, 2024",
    bio: "Charlie is a friendly and energetic pup who loves to play fetch! He was found near the Engineering Building and has been well-cared for by our campus community. He's great with people and gets along well with other dogs.",
    image: require("../assets/strays/charlie.png"),
    vaccinations: [
      { name: "Anti-Rabies", date: "Sept 15, 2025", status: "Completed" },
      { name: "Distemper", date: "Aug 20, 2025", status: "Completed" },
      { name: "Parvovirus", date: "Dec 1, 2025", status: "Scheduled" },
    ],
  },
  {
    id: 2,
    name: "Bella",
    breed: "Siamese Cat",
    gender: "Female",
    age: "~1.5 years",
    weight: "4.2 kg",
    location: "Science Complex",
    rescueDate: "September 5, 2024",
    bio: "Bella is a sweet and affectionate cat who loves quiet corners and gentle pets. She was rescued from the Science Complex rooftop and is looking for a calm, loving home.",
    image: require("../assets/strays/bella.png"),
    vaccinations: [
      { name: "FVRCP", date: "Oct 10, 2025", status: "Completed" },
      { name: "Rabies", date: "Oct 10, 2025", status: "Completed" },
    ],
  },
  {
    id: 3,
    name: "Rocky",
    breed: "Golden Retriever Mix",
    gender: "Male",
    age: "~3 years",
    weight: "28 kg",
    location: "Library Courtyard",
    rescueDate: "July 20, 2024",
    bio: "Rocky is a gentle giant with a heart of gold. He loves long walks and belly rubs. Found guarding the library steps, he’s ready for his forever campus family!",
    image: require("../assets/strays/rocky.png"),
    vaccinations: [
      { name: "Anti-Rabies", date: "Aug 1, 2025", status: "Completed" },
      { name: "DHPP", date: "July 25, 2025", status: "Completed" },
      { name: "Bordetella", date: "Jan 10, 2026", status: "Scheduled" },
    ],
  },
];