export const STRAYS = [
  {
    id: 1,
    name: "Charlie",
    breed: "Mixed Breed",
    gender: "Male",
    age: "~2 years",
    weight: "15 kg",
    location: "CEIT",
    rescueDate: "August 12, 2024",
    bio: "Charlie is a friendly and energetic pup who loves to play fetch! He was found near the Engineering Building and has been well-cared for by our campus community. He's great with people and gets along well with other dogs.",
    image: require("../assets/strays/charlie.png"),
    vaccinations: [
      { name: "Anti-Rabies", date: "Sept 15, 2025", status: "Completed" },
      { name: "Distemper", date: "Aug 20, 2025", status: "Completed" },
      { name: "Parvovirus", date: "Dec 1, 2025", status: "Scheduled" },
    ],
  },
  {
    id: 2,
    name: "Bella",
    breed: "Siamese Cat",
    gender: "Female",
    age: "~1.5 years",
    weight: "4.2 kg",
    location: "CAS",
    rescueDate: "September 5, 2024",
    bio: "Bella is a sweet and affectionate cat who loves quiet corners and gentle pets. She was rescued from the Science Complex rooftop and is looking for a calm, loving home.",
    image: require("../assets/strays/bella.png"),
    vaccinations: [
      { name: "FVRCP", date: "Oct 10, 2025", status: "Completed" },
      { name: "Rabies", date: "Oct 10, 2025", status: "Completed" },
    ],
  },
  {
    id: 3,
    name: "Rocky",
    breed: "Golden Retriever Mix",
    gender: "Male",
    age: "~3 years",
    weight: "28 kg",
    location: "University Library",
    rescueDate: "July 20, 2024",
    bio: "Rocky is a gentle giant with a heart of gold. He loves long walks and belly rubs. Found guarding the library steps, he’s ready for his forever campus family!",
    image: require("../assets/strays/rocky.png"),
    vaccinations: [
      { name: "Anti-Rabies", date: "Aug 1, 2025", status: "Completed" },
      { name: "DHPP", date: "July 25, 2025", status: "Completed" },
      { name: "Bordetella", date: "Jan 10, 2026", status: "Scheduled" },
    ],
  },
  {
    id: 4,
    name: "Mimi",
    breed: "Persian Mix",
    gender: "Female",
    age: "~2 years",
    weight: "5.8 kg",
    location: "Admin Building",
    rescueDate: "October 3, 2024",
    bio: "Mimi is a fluffy and calm cat with beautiful long fur. She was found hiding near the admin offices and enjoys sunny spots and gentle brushing. Looking for a quiet, loving home.",
    image: require("../assets/strays/mimi.png"),
    vaccinations: [
      { name: "FVRCP", date: "Nov 5, 2025", status: "Completed" },
      { name: "Rabies", date: "Nov 5, 2025", status: "Completed" },
      { name: "Deworming", date: "Feb 15, 2026", status: "Scheduled" },
    ],
  },
  {
    id: 5,
    name: "Duke",
    breed: "German Shepherd Mix",
    gender: "Male",
    age: "~4 years",
    weight: "35 kg",
    location: "Bleachers",
    rescueDate: "June 15, 2024",
    bio: "Duke is a loyal and protective dog who loves active playtime and long walks. Rescued from the sports area, he’s strong, smart, and ready to be your best adventure buddy!",
    image: require("../assets/strays/duke.png"),
    vaccinations: [
      { name: "Anti-Rabies", date: "July 20, 2025", status: "Completed" },
      { name: "DHPP", date: "July 15, 2025", status: "Completed" },
      { name: "Heartworm Prevention", date: "Mar 1, 2026", status: "Scheduled" },
    ],
  },
  {
    id: 6,
    name: "Luna",
    breed: "Siamese Mix",
    gender: "Female",
    age: "~1 year",
    weight: "3.9 kg",
    location: "Arts Building",
    rescueDate: "November 10, 2024",
    bio: "Luna is a playful and vocal kitten with striking blue eyes. She was found near the arts department and loves chasing toys and cuddling. Perfect for someone who wants an energetic companion!",
    image: require("../assets/strays/luna.png"),
    vaccinations: [
      { name: "FVRCP", date: "Dec 5, 2025", status: "Completed" },
      { name: "Rabies", date: "Dec 5, 2025", status: "Completed" },
    ],
  },
];